name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Publish
        run: dotnet publish -c Release -o publish


      - name: Fix base href for GitHub Pages
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          sed -i "s|<base href=\"/\" />|<base href=\"/$REPO_NAME/\" />|g" publish/wwwroot/index.html

      - name: Remove all integrity attributes (disable SRI)
        run: |
          find publish/wwwroot -type f -name '*.html' -exec sed -i 's/ integrity="[^"]*"//g' {} +
          find publish/wwwroot -type f -name '*.js' -exec sed -i 's/ integrity:"[^"]*",//g' {} +

      - name: Add .nojekyll
        run: touch publish/wwwroot/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: publish/wwwroot

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4